CREATE DATABASE projeto_back;

\c projeto_back;

CREATE TABLE lutadores (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) UNIQUE NOT NULL,
    categoria_peso VARCHAR(50) NOT NULL,
    alcance_cm INTEGER,
    estilo_principal VARCHAR(100),
    biografia TEXT,
    cartel_vitorias INTEGER DEFAULT 0,
    cartel_derrotas INTEGER DEFAULT 0,
    cartel_empate INTEGER DEFAULT 0,
    principais_conquistas TEXT,
    hall_da_fama BOOLEAN DEFAULT FALSE,
    destaque_home BOOLEAN DEFAULT FALSE,
    foto_url TEXT,
    genero VARCHAR(10) NOT NULL DEFAULT 'Masculino'
);
INSERT INTO lutadores (nome, categoria_peso, alcance_cm, estilo_principal, biografia, cartel_vitorias, cartel_derrotas, cartel_empate, principais_conquistas, hall_da_fama, destaque_home, foto_url, genero) VALUES
('Fabricio Werdum', 'Peso Pesado', 196, 'Jiu-Jitsu', 'Ex-campeao mundial dos pesos pesados do UFC, nascido em Porto Alegre.', 24, 9, 1, 'Campeao UFC Peso Pesado, Campeao Strikeforce', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2354533.png', 'Masculino'),
('Junior dos Santos', 'Peso Pesado', 198, 'Boxe', 'Ex-campeao dos pesos pesados do UFC, nascido em Salvador, conhecido como "Cigano".', 21, 10, 0, 'Campeao UFC Peso Pesado', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335725.png', 'Masculino'),
('Antonio Rodrigo Nogueira', 'Peso Pesado', 191, 'Jiu-Jitsu', 'Lenda do MMA mundial, "Minotauro", nascido em Vitoria da Conquista.', 34, 10, 1, 'Campeao Pride, Campeao Interino UFC', TRUE, FALSE, 'https://a.espncdn.com/i/headshots/mma/players/full/2335521.png', 'Masculino'),
('Glover Teixeira', 'Meio-Pesado', 193, 'Boxe', 'Ex-campeao meio-pesado do UFC, nascido em Sobralia, Minas Gerais.', 33, 9, 0, 'Campeao UFC Meio-Pesado', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2504929.png', 'Masculino'),
('Mauricio "Shogun" Rua', 'Meio-Pesado', 193, 'Muay Thai', 'Ex-campeao do UFC e Pride, nascido em Curitiba.', 27, 14, 1, 'Campeao UFC, Campeao Pride GP 2005', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335514.png', 'Masculino'),
('Lyoto Machida', 'Meio-Pesado', 188, 'Karate', 'Ex-campeao meio-pesado do UFC, nascido em Salvador.', 26, 12, 0, 'Campeao UFC Meio-Pesado', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335524.png', 'Masculino'),
('Anderson Silva', 'Peso Medio', 188, 'Muay Thai', 'Maior campeao da historia dos medios, nascido em Sao Paulo.', 34, 11, 0, 'Campeao UFC Peso Medio (16 defesas)', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335447.png', 'Masculino'),
('Alex Pereira', 'Peso Medio', 193, 'Kickboxing', 'Ex-campeao meio-pesado do UFC, nascido em Sao Bernardo do Campo.', 10, 2, 0, 'Campeao UFC Meio-Pesado, Ex-Campeao Glory Kickboxing', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4705658.png', 'Masculino'),
('Vitor Belfort', 'Peso Medio', 188, 'Boxe', 'Ex-campeao do UFC, nascido no Rio de Janeiro.', 26, 14, 0, 'Campeao UFC Peso Pesado', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2354057.png', 'Masculino'),
('Carlos Condit', 'Peso Meio-Medio', 188, 'Muay Thai', 'Ex-campeao interino do UFC, conhecido como "The Natural Born Killer", nascido em Albuquerque.', 32, 14, 0, 'Campeao Interino UFC Peso Meio-Medio', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335243.png', 'Masculino'),
('Demian Maia', 'Peso Meio-Medio', 185, 'Jiu-Jitsu', 'Lenda do Jiu-Jitsu no MMA, nascido em Sao Paulo.', 28, 11, 0, 'Desafiante ao titulo UFC', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335778.png', 'Masculino'),
('Thiago Alves', 'Peso Meio-Medio', 180, 'Muay Thai', 'Veterano brasileiro do UFC, nascido em Fortaleza.', 23, 14, 0, 'Desafiante ao titulo UFC', TRUE, FALSE, 'https://a.espncdn.com/i/headshots/mma/players/full/2335660.png', 'Masculino'),
('Charles Oliveira', 'Peso Leve', 188, 'Jiu-Jitsu', 'Ex-campeao peso leve do UFC, nascido em Sao Paulo.', 34, 9, 0, 'Campeao UFC Peso Leve, Mais finalizacoes UFC', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2504169.png', 'Masculino'),
('Renato Moicano', 'Peso Leve', 178, 'Jiu-Jitsu', 'Top contender brasileiro, "Moicano", nascido em Brasilia.', 18, 5, 1, 'Top 10 UFC Peso Leve', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3028863.png', 'Masculino'),
('Rafael dos Anjos', 'Peso Leve', 178, 'Jiu-Jitsu', 'Ex-campeao peso leve do UFC, nascido em Niteroi.', 32, 14, 0, 'Campeao UFC Peso Leve', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335687.png', 'Masculino'),
('Jose Aldo', 'Peso Pena', 178, 'Muay Thai', 'Rei dos penas, nascido em Manaus, lenda brasileira.', 31, 8, 0, 'Campeao UFC/WEC Peso Pena (9 defesas)', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2447641.png', 'Masculino'),
('Patricio Pitbull', 'Peso Pena', 170, 'Jiu-Jitsu', 'Lenda do Bellator, nascido em Natal.', 35, 6, 0, 'Campeao Bellator Peso Pena e Leve', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2532870.png', 'Masculino'),
('Edson Barboza', 'Peso Pena', 178, 'Muay Thai', 'Striker lendario do UFC, nascido em Nova Friburgo.', 23, 11, 0, 'Chute do ano UFC multiplas vezes', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2526299.png', 'Masculino'),
('Raphael Assuncao', 'Peso Galo', 170, 'Jiu-Jitsu', 'Veterano lendario do UFC, nascido em Natal.', 27, 9, 0, 'Top 5 UFC por anos', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2354364.png', 'Masculino'),
('Diego Lopes', 'Peso Pena', 178, 'Jiu-Jitsu', 'Revelacao brasileira no UFC, nascido em Manaus.', 24, 6, 0, 'Top 10 UFC Peso Pena', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4881999.png', 'Masculino'),
('Renan Barao', 'Peso Pena', 170, 'Jiu-Jitsu', 'Ex-campeao peso galo do UFC, nascido em Natal.', 34, 9, 0, 'Campeao UFC Peso Galo', TRUE, FALSE, 'https://a.espncdn.com/i/headshots/mma/players/full/2504550.png', 'Masculino'),
('Alexandre Pantoja', 'Peso Mosca', 177, 'Jiu-Jitsu', 'Atual campeao peso mosca do UFC, nascido no Rio de Janeiro.', 26, 5, 0, 'Campeao UFC Peso Mosca atual', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2560746.png', 'Masculino'),
('Deiveson Figueiredo', 'Peso Mosca', 178, 'Jiu-Jitsu', 'Ex-campeao peso mosca do UFC, nascido em Soure, Para.', 22, 3, 1, 'Campeao UFC Peso Mosca, 4 defesas', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4189320.png', 'Masculino'),
('Jussier Formiga', 'Peso Mosca', 173, 'Jiu-Jitsu', 'Veterano brasileiro do UFC, nascido em Fortaleza.', 23, 7, 0, 'Multiplas disputas de titulo', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2560740.png', 'Masculino'),
('Cris Cyborg', 'Peso Pena', 173, 'Muay Thai', 'Lenda do MMA feminino, ex-campea UFC, nascida em Curitiba.', 26, 2, 1, 'Campea UFC/Strikeforce/Invicta/Bellator', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2354564.png', 'Feminino'),
('Amanda Nunes', 'Peso Pena', 175, 'Boxe', 'Maior lutadora da historia do MMA, nascida em Salvador.', 22, 5, 0, 'Campea dupla UFC (Galo/Pena), GOAT feminino', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2516131.png', 'Feminino'),
('Norma Dumont', 'Peso Pena', 170, 'Jiu-Jitsu', 'Top contender brasileira, nascida em Belo Horizonte.', 10, 2, 0, 'Top 10 UFC Peso Pena', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4418784.png', 'Feminino'),
('Bethe Correia', 'Peso Galo', 165, 'Boxing', 'Pioneira brasileira no UFC feminino, nascida em Campina Grande.', 11, 5, 1, 'Desafiante ao titulo UFC', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3081041.png', 'Feminino'),
('Ketlen Vieira', 'Peso Galo', 175, 'Jiu-Jitsu', 'Top contender brasileira, nascida em Manaus.', 13, 3, 0, 'Top 5 UFC Peso Galo', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4039865.png', 'Feminino'),
('Mayra Bueno Silva', 'Peso Galo', 168, 'Jiu-Jitsu', 'Top contender brasileira, nascida em Sao Paulo.', 10, 2, 1, 'Top 10 UFC Peso Galo', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4371001.png', 'Feminino'),
('Priscila Cachoeira', 'Peso Mosca', 165, 'Muay Thai', 'Lutadora brasileira no peso mosca, conhecida como "Pedrita", nascida no Rio de Janeiro.', 12, 4, 0, 'Top 15 UFC Peso Mosca', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4277049.png', 'Feminino'),
('Jennifer Maia', 'Peso Mosca', 163, 'Jiu-Jitsu', 'Ex-desafiante ao titulo, nascida em Curitiba.', 20, 9, 1, 'Desafiante ao titulo UFC', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3022348.png', 'Feminino'),
('Viviane Araujo', 'Peso Mosca', 163, 'Muay Thai', 'Top contender brasileira, nascida no Rio de Janeiro.', 12, 4, 0, 'Top 5 UFC Peso Mosca', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4379362.png', 'Feminino'),
('Claudia Gadelha', 'Peso Palha', 165, 'Jiu-Jitsu', 'Pioneira brasileira no UFC feminino, nascida em Mossoro.', 18, 5, 0, 'Multiplas disputas de titulo UFC', TRUE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3011878.png', 'Feminino'),
('Amanda Ribas', 'Peso Palha', 165, 'Jiu-Jitsu', 'Estrela brasileira do UFC, nascida em Varginha.', 12, 4, 0, 'Top 10 UFC Peso Palha', FALSE, FALSE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4221863.png', 'Feminino'),
('Jessica Andrade', 'Peso Palha', 165, 'Muay Thai', 'Ex-campea peso palha do UFC, nascida em Umuarama.', 25, 9, 0, 'Ex-campea UFC Peso Palha', TRUE, TRUE, 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3024395.png', 'Feminino');
